# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Time at which the profile was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time at which the profile was updated'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Time at which the profile was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time at which the profile was updated'),
        ),
        migrations.AddField(
            model_name='rsvpperson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Time at which the profile was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvpperson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time at which the profile was updated'),
        ),
    ]
