# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_auto_20170903_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='name',
            field=models.CharField(default='', help_text='Name of the people the RSVP is intended for', max_length=256),
            preserve_default=False,
        ),
    ]
