# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_rsvp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvpperson',
            name='dietary_other',
            field=models.CharField(blank=True, help_text='Other Dietary Restrictions', max_length=256),
        ),
        migrations.AlterField(
            model_name='rsvpperson',
            name='special_requests',
            field=models.CharField(blank=True, help_text='Any other special requests for the person', max_length=256),
        ),
    ]
