# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_auto_20170903_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='user',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='profile',
            field=models.OneToOneField(help_text='Profile with which the RSVP is associated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvp', to='wedding.Profile'),
        ),
    ]
