# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_auto_20170903_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='name',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='last_names',
            field=models.CharField(default='', help_text='Comma-separated last names of the people the RSVP is intended for', max_length=256),
            preserve_default=False,
        ),
    ]
