# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_auto_20170903_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvpperson',
            name='rsvp',
            field=models.ForeignKey(help_text='Link back to overall RSVP', on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_person', to='wedding.RSVP'),
        ),
    ]
